INSERT INTO tourist_spots (municipality_id, name, description, address, latitude, longitude, image_url, nearby_dining, nearby_gas_stations, status, created_at, updated_at) VALUES
-- Lingayen
(1, 'Lingayen Beach', 'A pristine beach famous for sunrise views and water sports. Perfect for swimming and beach relaxation with golden sand shores.', 'Barangay Bonuan, Lingayen', 16.0146, 120.2327, 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500', 'Bonuan Grill House, Seafood Restaurants along the beach', 'Caltex Station, Shell Gas Station near town center', 'active', NOW(), NOW()),
(1, 'Dagupan Zondag Market', 'A vibrant public market showcasing local crafts, fresh produce, and handicrafts. Popular for shopping local Pangasinan souvenirs.', 'Perez Boulevard, Lingayen', 16.0178, 120.2295, 'https://images.unsplash.com/photo-1488459716781-6815aa17b773?w=500', 'Market stalls with local food, Nearby restaurants', 'Petron Gas Station, Shell near Dagupan', 'active', NOW(), NOW()),
-- Basista
(2, 'Basista Church', 'A historic Roman Catholic church showcasing beautiful architecture and cultural heritage. Important religious landmark of the municipality.', 'Plaza Centro, Basista', 16.0427, 120.2436, 'https://images.unsplash.com/photo-1548438294-1716fc27c6ca?w=500', 'Church grounds cafes, Nearby restaurants', 'Town center gas stations', 'active', NOW(), NOW()),
(2, 'Agricultural Farm Areas', 'Vast agricultural lands showcasing rice fields and vegetable farming. Great for rural tourism and learning about local farming methods.', 'Agricultural Zone, Basista', 16.0450, 120.2400, 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=500', 'Farm-to-table restaurants, Local food vendors', 'Gas stations in town center', 'active', NOW(), NOW()),
-- Urbiztondo
(3, 'Urbiztondo Beach Surf Spot', 'World-class surfing destination with consistent waves. Home to professional and amateur surfers, especially during northwest monsoon.', 'Barangay Poro Point, Urbiztondo', 16.0713, 120.2189, 'https://images.unsplash.com/photo-1502933691298-84fc14542831?w=500', 'Surf cafes, Beachside restaurants, Poro Point dining', 'Caltex Urbiztondo, Shell Gas Station', 'active', NOW(), NOW()),
(3, 'Poro Point Lighthouse', 'Iconic lighthouse offering panoramic views of the Lingayen Gulf and surrounding coastal areas. Popular photography spot.', 'Poro Point, Urbiztondo', 16.0750, 120.2150, 'https://images.unsplash.com/photo-1544551763-92ab472cad5d?w=500', 'Poro Point cafe, Beachside grills', 'Gas stations near Poro Point', 'active', NOW(), NOW()),
-- Aguilar
(4, 'Aguilar Public Market', 'Historic public market offering fresh local products, handicrafts, and authentic Pangasinan goods.', 'Town Plaza, Aguilar', 15.9896, 120.2553, 'https://images.unsplash.com/photo-1488459716781-6815aa17b773?w=500', 'Market food stalls, Local eateries', 'Town center gas stations', 'active', NOW(), NOW()),
(4, 'Aguilar Town Hall Park', 'Beautiful municipal park with verdant grounds, perfect for leisure walks and cultural gatherings.', 'Municipal Hall Grounds, Aguilar', 15.9920, 120.2540, 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=500', 'Nearby cafes, Food stalls', 'Gas stations in town', 'active', NOW(), NOW()),
-- Bugallon
(5, 'Bugallon Church and Plaza', 'Historic church with traditional architecture surrounded by a public plaza. Important cultural and religious landmark.', 'Plaza Centro, Bugallon', 16.0574, 120.1905, 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=500', 'Restaurants near plaza, Local food vendors', 'Petron Station, Gasoline stations nearby', 'active', NOW(), NOW()),
(5, 'Bugallon Fishponds', 'Extensive aquaculture areas showcasing traditional fish farming. Beautiful landscape and sustainable aquaculture practices.', 'Fishpond Area, Bugallon', 16.0550, 120.1880, 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=500', 'Fishery-related restaurants, Farm stores', 'Local gas stations', 'active', NOW(), NOW()),
-- Binmaley
(6, 'Binmaley Church', 'Centuries-old baroque church with stunning architecture. Important religious and historical site of the municipality.', 'Plaza Rizal, Binmaley', 15.9789, 120.1835, 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=500', 'Cathedral ground vendors, Nearby restaurants', 'Gas stations in plaza area', 'active', NOW(), NOW()),
(6, 'Binmaley Rice Fields', 'Expansive rice terraces and agricultural lands. Scenic views of traditional farming and rural landscape beauty.', 'Agricultural lands, Binmaley', 15.9750, 120.1800, 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=500', 'Farm stands, Agricultural product shops', 'Gas stations near town', 'active', NOW(), NOW()),
-- Labrador
(7, 'Labrador Beach', 'Serene coastal beach with peaceful atmosphere, perfect for swimming and relaxation away from crowded areas.', 'Barangay Tabuc Tubig, Labrador', 16.0045, 120.2087, 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500', 'Beachside eateries, Local seafood restaurants', 'Shell Gas Station, Caltex nearby', 'active', NOW(), NOW()),
(7, 'Labrador Fish Market', 'Bustling wet market showcasing fresh catches and local fishing industry. Experience authentic coastal commerce.', 'Market Area, Labrador', 16.0060, 120.2100, 'https://images.unsplash.com/photo-1488459716781-6815aa17b773?w=500', 'Market stalls, Fish-related food vendors', 'Gas stations in town', 'active', NOW(), NOW()),
-- Mangatarem
(8, 'Mangatarem Church', 'Old church with historical significance and beautiful structure. Central gathering place for the community.', 'Plaza Rizal, Mangatarem', 15.9523, 120.2348, 'https://images.unsplash.com/photo-1548438294-1716fc27c6ca?w=500', 'Church vicinity restaurants, Local food stalls', 'Gas stations near plaza', 'active', NOW(), NOW()),
(8, 'Mangatarem Riverbanks', 'Scenic riverbank area perfect for nature walks and observation of local ecosystem. Peaceful spot for relaxation.', 'Riverbank Area, Mangatarem', 15.9540, 120.2330, 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=500', 'Riverside cafes, Picnic areas', 'Gas stations in town', 'active', NOW(), NOW());
